### ISSUE TITLE
KeyError: 'brand'

### ISSUE THREAD

**Issue by daglaroglou** [suhanna/System_info#10]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python310\lib\site-packages\system_info\sysinfo.py", line 230, in <module>
    sysInfo = os_info.systemSpec()
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python310\lib\site-packages\system_info\sysinfo.py", line 55, in systemSpec
    data["Processor"] = cinfo['brand']
KeyError: 'brand'

**Comment by djjudas21** [comment]
Also seeing this on Linux

```
Traceback (most recent call last):
  File "/home/jonathan/git/auto-node-label/main.py", line 9, in <module>
    from system_info import sysinfo
  File "/home/jonathan/.cache/pypoetry/virtualenvs/autonodelabel-GJIqH3kF-py3.11/lib/python3.11/site-packages/system_info/sysinfo.py", line 230, in <module>
    sysInfo = os_info.systemSpec()
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan/.cache/pypoetry/virtualenvs/autonodelabel-GJIqH3kF-py3.11/lib/python3.11/site-packages/system_info/sysinfo.py", line 55, in systemSpec
    data["Processor"] = cinfo['brand']
                        ~~~~~^^^^^^^^^
KeyError: 'brand'
```

**Comment by cnzyan** [comment]
edit sysinfo.py line 55:
data["Processor"] = cinfo['brand']
-->
data["Processor"] = cinfo['brand_raw']

**Comment by suhanna** [comment]
The issue has been resolved, and version v2.0.3 has been released.
